typography_spectrum: 0.5331816761221478
color:
  brandStrength: 0.8143434133259857
  lightness: 0.537913980674515
  saturation: 0.5312146112841029
  rhythmicContrast: 0.798132665305131
  brandColors:
    - '#596898'
    - '#EE2123'
    - '#12100F'
    - '#EABE32'
    - '#FFFFFF'
github: true
layout_spectrum: 0.44950208412584763
analytics:
  twitter: personal
author:
  name: Allan Calford
  email: dacalford@gmail.com
  url: thegrid.ai/toba
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca32b1da-0693-4ef1-ae0a-d88b8f2aafd5.png
name: TOBA
navigation:
  - name: About TOBA
    id: d3a8944a-8752-43d6-bcf5-598ddaa64294
    type: content
title: The Old Bastards Association
content: []
description: Youth is wasted on the Young
