layout_spectrum: 0.44950208412584763
typography_spectrum: 0.5331816761221478
color:
  brandStrength: 0.8143434133259857
  lightness: 0.537913980674515
  saturation: 0.5312146112841029
  rhythmicContrast: 0.798132665305131
  brandColors:
    - '#596898'
    - '#EE2123'
    - '#12100F'
    - '#EABE32'
    - '#FFFFFF'
github: true
analytics:
  twitter: personal
author:
  name: Allan Calford
  email: dacalford@gmail.com
  url: thegrid.ai/toba
name: TOBA
title: The Old Bastards Association
content: []
description: Youth is wasted on the Young
